//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvaluacionCliente {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EvaluacionCliente.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se han limpiado los datos.
        /// </summary>
        internal static string DatosLimpios {
            get {
                return ResourceManager.GetString("DatosLimpios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proceso finalizado correctamente.
        /// </summary>
        internal static string FinalizadoCorrectamente {
            get {
                return ResourceManager.GetString("FinalizadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se guardó el registro.
        /// </summary>
        internal static string GuardaRegistro {
            get {
                return ResourceManager.GetString("GuardaRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay datos de acceso, revise si el usuario existe o si el usuario y contraseña ingresado son correctos.
        /// </summary>
        internal static string NoAcceso {
            get {
                return ResourceManager.GetString("NoAcceso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay datos para sincronizar.
        /// </summary>
        internal static string NoDatosSincroniza {
            get {
                return ResourceManager.GetString("NoDatosSincroniza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proceso no finalizó correctamente.
        /// </summary>
        internal static string NoFinalizaProceso {
            get {
                return ResourceManager.GetString("NoFinalizaProceso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese el nombre del dispositivo.
        /// </summary>
        internal static string NombreDispositivo {
            get {
                return ResourceManager.GetString("NombreDispositivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre del dispositivo no puede ser en blanco o nulo.
        /// </summary>
        internal static string NombreDispositivoVacio {
            get {
                return ResourceManager.GetString("NombreDispositivoVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El dispositivo no tiene nombre asignado.
        /// </summary>
        internal static string SinNombre {
            get {
                return ResourceManager.GetString("SinNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El dispositivo no tiene asignado sucursal.
        /// </summary>
        internal static string SinSucursal {
            get {
                return ResourceManager.GetString("SinSucursal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese el identificador para sucursal.
        /// </summary>
        internal static string Sucursal {
            get {
                return ResourceManager.GetString("Sucursal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La sucursal no puede ser en blanco o nulo.
        /// </summary>
        internal static string SucursalVacia {
            get {
                return ResourceManager.GetString("SucursalVacia", resourceCulture);
            }
        }
    }
}
